[2024-07-13T05:01:54.716+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscraping.Start_Janusgraph manual__2024-07-13T04:56:51.966217+00:00 [queued]>
[2024-07-13T05:01:54.725+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscraping.Start_Janusgraph manual__2024-07-13T04:56:51.966217+00:00 [queued]>
[2024-07-13T05:01:54.727+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-13T05:01:54.740+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Start_Janusgraph> on 2024-07-13 04:56:51.966217+00:00
[2024-07-13T05:01:54.747+0000] {standard_task_runner.py:60} INFO - Started process 156 to run task
[2024-07-13T05:01:54.756+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Webscraping', 'Start_Janusgraph', 'manual__2024-07-13T04:56:51.966217+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/webscrape_dag.py', '--cfg-path', '/tmp/tmpi3dtckr3']
[2024-07-13T05:01:54.761+0000] {standard_task_runner.py:88} INFO - Job 58: Subtask Start_Janusgraph
[2024-07-13T05:01:54.865+0000] {task_command.py:423} INFO - Running <TaskInstance: Webscraping.Start_Janusgraph manual__2024-07-13T04:56:51.966217+00:00 [running]> on host 0d386e3ce452
[2024-07-13T05:01:54.953+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Webscraping' AIRFLOW_CTX_TASK_ID='Start_Janusgraph' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T04:56:51.966217+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T04:56:51.966217+00:00'
[2024-07-13T05:01:54.954+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-13T05:01:54.954+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker start janusgraph-server']
[2024-07-13T05:01:54.965+0000] {subprocess.py:86} INFO - Output:
[2024-07-13T05:01:54.982+0000] {subprocess.py:93} INFO - permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.44/containers/janusgraph-server/start": dial unix /var/run/docker.sock: connect: permission denied
[2024-07-13T05:01:54.982+0000] {subprocess.py:93} INFO - Error: failed to start containers: janusgraph-server
[2024-07-13T05:01:54.983+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-13T05:01:54.995+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-13T05:01:54.998+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Webscraping, task_id=Start_Janusgraph, execution_date=20240713T045651, start_date=20240713T050154, end_date=20240713T050154
[2024-07-13T05:01:55.015+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 58 for task Start_Janusgraph (Bash command failed. The command returned a non-zero exit code 1.; 156)
[2024-07-13T05:01:55.027+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-13T05:01:55.055+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
