[2024-07-13T04:56:53.317+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscraping.Start_Janusgraph manual__2024-07-13T04:56:51.966217+00:00 [queued]>
[2024-07-13T04:56:53.328+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscraping.Start_Janusgraph manual__2024-07-13T04:56:51.966217+00:00 [queued]>
[2024-07-13T04:56:53.328+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-13T04:56:53.341+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Start_Janusgraph> on 2024-07-13 04:56:51.966217+00:00
[2024-07-13T04:56:53.346+0000] {standard_task_runner.py:60} INFO - Started process 79 to run task
[2024-07-13T04:56:53.349+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Webscraping', 'Start_Janusgraph', 'manual__2024-07-13T04:56:51.966217+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/webscrape_dag.py', '--cfg-path', '/tmp/tmpyso4akip']
[2024-07-13T04:56:53.350+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask Start_Janusgraph
[2024-07-13T04:56:53.409+0000] {task_command.py:423} INFO - Running <TaskInstance: Webscraping.Start_Janusgraph manual__2024-07-13T04:56:51.966217+00:00 [running]> on host 0d386e3ce452
[2024-07-13T04:56:53.512+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Webscraping' AIRFLOW_CTX_TASK_ID='Start_Janusgraph' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T04:56:51.966217+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T04:56:51.966217+00:00'
[2024-07-13T04:56:53.513+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-13T04:56:53.515+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker start janusgraph-server']
[2024-07-13T04:56:53.525+0000] {subprocess.py:86} INFO - Output:
[2024-07-13T04:56:53.873+0000] {subprocess.py:93} INFO - permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.44/containers/janusgraph-server/start": dial unix /var/run/docker.sock: connect: permission denied
[2024-07-13T04:56:53.874+0000] {subprocess.py:93} INFO - Error: failed to start containers: janusgraph-server
[2024-07-13T04:56:53.875+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-13T04:56:53.891+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-13T04:56:53.895+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Webscraping, task_id=Start_Janusgraph, execution_date=20240713T045651, start_date=20240713T045653, end_date=20240713T045653
[2024-07-13T04:56:53.911+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 57 for task Start_Janusgraph (Bash command failed. The command returned a non-zero exit code 1.; 79)
[2024-07-13T04:56:53.929+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-13T04:56:53.953+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
