[2024-07-17T21:10:32.239+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscraping.Pre-Scrape_script manual__2024-07-17T08:25:37.156618+00:00 [queued]>
[2024-07-17T21:10:32.249+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscraping.Pre-Scrape_script manual__2024-07-17T08:25:37.156618+00:00 [queued]>
[2024-07-17T21:10:32.249+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 6
[2024-07-17T21:10:32.264+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Pre-Scrape_script> on 2024-07-17 08:25:37.156618+00:00
[2024-07-17T21:10:32.267+0000] {standard_task_runner.py:60} INFO - Started process 59 to run task
[2024-07-17T21:10:32.270+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Webscraping', 'Pre-Scrape_script', 'manual__2024-07-17T08:25:37.156618+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/webscrape_dag.py', '--cfg-path', '/tmp/tmpsnuiyh8l']
[2024-07-17T21:10:32.271+0000] {standard_task_runner.py:88} INFO - Job 162: Subtask Pre-Scrape_script
[2024-07-17T21:10:32.324+0000] {task_command.py:423} INFO - Running <TaskInstance: Webscraping.Pre-Scrape_script manual__2024-07-17T08:25:37.156618+00:00 [running]> on host d02a81fe6cad
[2024-07-17T21:10:32.423+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Webscraping' AIRFLOW_CTX_TASK_ID='Pre-Scrape_script' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T08:25:37.156618+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T08:25:37.156618+00:00'
[2024-07-17T21:10:32.424+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-17T21:10:32.424+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 pre_scrape.py']
[2024-07-17T21:10:32.433+0000] {subprocess.py:86} INFO - Output:
[2024-07-17T21:10:32.456+0000] {subprocess.py:93} INFO - python3: can't open file 'pre_scrape.py': [Errno 2] No such file or directory
[2024-07-17T21:10:32.458+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-07-17T21:10:32.469+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-07-17T21:10:32.473+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Webscraping, task_id=Pre-Scrape_script, execution_date=20240717T082537, start_date=20240717T211032, end_date=20240717T211032
[2024-07-17T21:10:32.489+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 162 for task Pre-Scrape_script (Bash command failed. The command returned a non-zero exit code 2.; 59)
[2024-07-17T21:10:32.524+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T21:10:32.548+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
