[2024-07-16T07:59:53.342+0000] {scheduler_job_runner.py:1575} WARNING - Marking task instance <TaskInstance: Webscraping.Pre-Scrape_script manual__2024-07-16T07:42:26.517176+00:00 [queued]> stuck in queued as failed. If the task instance has available retries, it will be retried.
[2024-07-16T07:59:53.807+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Webscraping.Pre-Scrape_script manual__2024-07-16T07:42:26.517176+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
